export interface Token {
  readonly name: `--${string}`
  readonly variable: string
}

function token(name: `--${string}`): Token {
  return { name, variable: `var(${name})` }
}

export const tokens = {
  colorText: token('--color-text'),
  colorTextMuted: token('--color-text-muted'),
  colorSurface: token('--color-surface'),
  colorSurfaceRaised: token('--color-surface-raised'),
  colorSurfacePanel: token('--color-surface-panel'),
  colorBorder: token('--color-border'),
  colorAccent: token('--color-accent'),
  colorAccentStrong: token('--color-accent-strong'),
  colorOnAccent: token('--color-on-accent'),
  colorFocusRing: token('--color-focus-ring'),
  colorSurfaceActive: token('--color-surface-active'),
  colorOnSurfaceActive: token('--color-on-surface-active'),
  colorIndicator: token('--color-indicator'),
  colorDanger: token('--color-danger'),
  colorKerf: token('--color-kerf'),
  colorInkBody: token('--color-ink-body'),
  colorInkEmphasis: token('--color-ink-emphasis'),
  colorInkLabel: token('--color-ink-label'),
  colorInkSecondary: token('--color-ink-secondary'),
  colorInkInstrument: token('--color-ink-instrument'),
  colorInkEngraved: token('--color-ink-engraved'),
  colorInkDormant: token('--color-ink-dormant'),
  colorInkGhost: token('--color-ink-ghost'),
  space1: token('--space-1'),
  space2: token('--space-2'),
  space3: token('--space-3'),
  space4: token('--space-4'),
  space5: token('--space-5'),
  space6: token('--space-6'),
  space7: token('--space-7'),
  sizeTargetMin: token('--size-target-min'),
  sizeTargetMinTouch: token('--size-target-min-touch'),
  sizeControlIcon: token('--size-control-icon'),
  sizeControlHeight: token('--size-control-height'),
  sizeRowCompact: token('--size-row-compact'),
  sizePanelDockedWidth: token('--size-panel-docked-width'),
  sizeHeroBand: token('--size-hero-band'),
  radiusSm: token('--radius-sm'),
  radiusMd: token('--radius-md'),
  radiusPill: token('--radius-pill'),
  radiusSquare: token('--radius-square'),
  borderWidthResting: token('--border-width-resting'),
  borderWidthActive: token('--border-width-active'),
  borderWidthFocusRing: token('--border-width-focus-ring'),
  borderWidthScribe: token('--border-width-scribe'),
  strokeIcon: token('--stroke-icon'),
  fontSizeXs: token('--font-size-xs'),
  fontSizeSm: token('--font-size-sm'),
  fontSizeMd: token('--font-size-md'),
  fontSizeLg: token('--font-size-lg'),
  fontSizeXl: token('--font-size-xl'),
  fontSize2xl: token('--font-size-2xl'),
  fontSize3xl: token('--font-size-3xl'),
  lineHeightPanel: token('--line-height-panel'),
  lineHeightProse: token('--line-height-prose'),
  letterSpacingStamped: token('--letter-spacing-stamped'),
  fontWeightRegular: token('--font-weight-regular'),
  fontWeightMedium: token('--font-weight-medium'),
  fontWeightSemibold: token('--font-weight-semibold'),
  fontWeightBold: token('--font-weight-bold'),
  fontFamilyUi: token('--font-family-ui'),
  fontFamilyHeading: token('--font-family-heading'),
  fontFamilyMono: token('--font-family-mono'),
  elevationFlat: token('--elevation-flat'),
  elevationRaised: token('--elevation-raised'),
  elevationOverlay: token('--elevation-overlay'),
  textureGrainOpacity: token('--texture-grain-opacity'),
  motionDuration: token('--motion-duration'),
  motionDurationMax: token('--motion-duration-max'),
  motionDurationDetent: token('--motion-duration-detent'),
  motionEasing: token('--motion-easing'),
} as const

export const tokenList: readonly Token[] = Object.values(tokens)
